### PR TITLE
 1st commit testing it by adding contact page -(trial)

### PR DESCRIPTION
**Pull request by simranhuddedar03**
-added contact page just for the trial

### CODE REVIEW

**Comment by simranhuddedar03** [comment]
1 Added one entire contact page .
2 created menu page and linked it in menu tag 
integration of chatbot in landing page

**Comment by simranhuddedar03** [comment]
In the next commit , I did some more modifications in the files . and added few missing resources that could help the community out there

**Comment by daneerakshita** [comment]
Thank you for fixing the unresponsive menu page! it really helped

**Comment by daneerakshita** [comment]
> In the next commit , I did some more modifications in the files . and added few missing resources that could help the community out there

Great!

**Comment by daneerakshita** [comment]
> 1 Added one entire contact page . 2 created menu page and linked it in menu tag integration of chatbot in landing page

The chatbot really helps with the user interaction!

**Comment by simranhuddedar03** [comment]
Thank you

**Pull request merged**
